# Generated by Django 2.0.2 on 2019-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_token', models.CharField(max_length=32)),
                ('line_id', models.CharField(max_length=33)),
                ('timestamp', models.DateTimeField()),
                ('hwid', models.CharField(max_length=10)),
                ('enter_or_leave', models.CharField(max_length=5)),
            ],
        ),
    ]
