# Generated by Django 2.0.2 on 2019-03-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0002_beacon_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user_master',
            name='num_entry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='current_entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eems.User_Master'),
        ),
    ]
