# Generated by Django 2.0.2 on 2019-03-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0003_auto_20190310_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='user_img',
            field=models.URLField(default='', max_length=250),
        ),
    ]
