# Generated by Django 2.0.2 on 2019-03-11 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0004_user_master_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_entry',
            name='user',
        ),
        migrations.AddField(
            model_name='current_entry',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_entry',
            name='leave_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_entry',
            name='line_id',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AddField(
            model_name='current_entry',
            name='line_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='current_entry',
            name='user_img',
            field=models.URLField(default='', max_length=250),
        ),
    ]
