# Generated by Django 2.0.2 on 2019-03-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0006_auto_20190316_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Leave_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField()),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eems.User_Master')),
            ],
        ),
        migrations.CreateModel(
            name='Today_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eems.User_Master')),
            ],
        ),
    ]
