# Generated by Django 2.0.2 on 2019-03-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0007_entry_leave_log_today_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_leave_log',
            name='log_id',
        ),
    ]
