# Generated by Django 2.0.2 on 2019-03-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0008_remove_entry_leave_log_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='user_id',
        ),
    ]
