# Generated by Django 2.0.2 on 2019-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0009_remove_user_master_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=32)),
                ('line_id', models.CharField(max_length=33)),
                ('entry_day', models.DateTimeField()),
            ],
        ),
    ]
