# Generated by Django 2.0.2 on 2019-03-31 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0010_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations_Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eems.Reservations')),
            ],
        ),
    ]
