# Generated by Django 2.0.2 on 2019-04-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0011_reservations_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='entry_day',
            field=models.CharField(max_length=10),
        ),
    ]
