# Generated by Django 2.0.2 on 2019-04-21 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0012_auto_20190407_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='leave_time',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='num_entry',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='user_img',
        ),
    ]
