# Generated by Django 2.0.2 on 2019-04-21 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eems', '0013_auto_20190421_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='company',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user_master',
            name='department',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user_master',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_master',
            name='leave_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_master',
            name='num_entry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_master',
            name='user_img',
            field=models.URLField(default='', max_length=250),
        ),
    ]
